import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@mantine/core/styles.css"
import { MantineProvider, ColorSchemeScript } from "@mantine/core"
import { theme } from "@/theme"
import "./globals.css"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })

export const metadata: Metadata = {
	title: "Insite",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<head>
				<ColorSchemeScript />
				<meta
					name='viewport'
					content='minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no'
				/>
				<meta
					httpEquiv='X-UA-Compatible'
					content='IE=edge'
				/>
				<link
					rel='shortcut icon'
					href='/favicon.svg'
				/>
			</head>
			<body className={inter.className}>
				<MantineProvider theme={theme}>{children}</MantineProvider>
			</body>
		</html>
	)
}
